<?php
$title = 'Add new spending';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$store = $form->get('store');
$store->setAttribute('class', 'form-control');
$store->setAttribute('placeholder', 'Store name');

// This provides a default CSS class and placeholder text for the artist element:
$price = $form->get('price');
$price->setAttribute('class', 'form-control');
$price->setAttribute('placeholder', 'Price');

$date = $form->get('date');
$date->setAttribute('class', 'form-control');
$date->setAttribute('placeholder', 'Date');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('hako', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($store) ?>
    <?= $this->formElement($store) ?>
    <?= $this->formElementErrors()->render($store, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($price) ?>
    <?= $this->formElement($price) ?>
    <?= $this->formElementErrors()->render($price, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($date) ?>
    <?= $this->formElement($date) ?>
    <?= $this->formElementErrors()->render($date, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();